@baseUrl = http://localhost:3000/api

# AUTH

# @name register
POST {{baseUrl}}/auth/register 
Content-Type: application/x-www-form-urlencoded
 
name=Tri Nguyen
&email=tricdt5.arse1@gmail.com
&password=123456
&cf_password=123456

###

# @name login
POST {{baseUrl}}/auth/login 
Content-Type: application/x-www-form-urlencoded
 
email=tricdt@gmail.com
&password=123456

###

# @name accessToken
GET {{baseUrl}}/auth/accessToken
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZmU0YTEzNDM5ZmRlMmI3YWU5OWEzOCIsImlhdCI6MTY2MDg3NzM3OCwiZXhwIjoxNjYxNDgyMTc4fQ.4S2EdiQt717sYxHkwF3RCjEvKfB0M5F0Fd4edPkBBOU;
